language: java
sudo: false
install: true

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "nroduit-github"
    token: "0c4c3860461d7d1098d51dfc52ec19d886025323"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
